### ISSUE TITLE
Dutch language option disappears when reloading after switching to English

### ISSUE THREAD

**Issue by Marthijs-Berfelo** [Marthijs-Berfelo/buddy-harmony#54]

**Comment by xavier-kong** [comment]
Hey I noticed in the live demo, after reloading, not only does the dutch language option disappear, the app language also reverts to dutch even though english is selected. Is this the same bug? 

I am interested in contributing to this issue.

**Comment by Marthijs-Berfelo** [comment]
@xavier-kong yes this is related. 
Please feel free to contribute.

You should be able to create a pull request after forking.

Sorry the contribution guide is not completed.

**Comment by xavier-kong** [comment]
@Marthijs-Berfelo I have a fix for the issues, do you have any preference on how you want to commit message and PR to be formatted?

**Comment by Marthijs-Berfelo** [comment]
@xavier-kong Great! :smiley: 

Nothing fancy regarding formatting. A description of the change and a reference to the issue it relates to so it will be linked automatically: see [github: link a pull-request](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by Marthijs-Berfelo** [comment]
@all-contributors add @xavier-kong for code
